version: 2.1
jobs:
  db-migrations:
    parameters:
      rap_env_prefix:
        type: string
        default: "local"
    working_directory: /app
    docker:
      - image: java:8
    environment:
        DB_HOST: << parameters.rap_env_prefix >>_DB_HOST
        DB_PORT: << parameters.rap_env_prefix >>_DB_PORT
        DB_NAME: << parameters.rap_env_prefix >>_DB_NAME
        DB_USERNAME: << parameters.rap_env_prefix >>_DB_USERNAME
        DB_PASSWORD: << parameters.rap_env_prefix >>_DB_PASSWORD
        CHANGELOG_FILE_PATH: "db/changelog.yml"
        LIQUIBASE_VERSION: 3.10.0
        MYSQL_CONNECTOR_VERSION: 8.0.20
    steps:
      - run:
          name: "Setup custom environment variables"
          command: echo $<< parameters.rap_env_prefix >>_DB_HOST

workflows:
  build-and-deploy-backend:
    jobs:
      - db-migrations:
          name: db-migrations-dev
          rap_env_prefix: "$ENV_DEV"
      - db-migrations:
          name: db-migrations-qa
          rap_env_prefix: QA
